name: build-macos

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-osx:
    runs-on: macos-12
    strategy:
        matrix:
          cfg:
          - {target: osx}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v2
    - name: rm-dev
      run: sudo rm -rf /Library/Developer
    - name: Build
      run: scripts/ci/osx/build.sh
      env:
        DEVELOPER_DIR: "/Applications/Xcode_13.4.1.app/Contents/Developer"
        SDKROOT: "/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
