name: build-macos

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-osx:
    runs-on: macos-12
    strategy:
        matrix:
          cfg:
          - {target: osx}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v2
    - name: Clone OF 
      id: clone-of
      shell: bash
      run: cd .. 
           git clone --depth=1 https://github.com/openframeworks/openFrameworks
    - name: Check OF
      shell: bash
      run: ls ..
    - name: Cache compile
      id: cache-compile
      uses: actions/cache@v3
      env:
        cache-name: cache-keep-compile
      with:
        path: ../openFrameworks/libs/openFrameworksCompiled/lib/osx/**/
        key: ${{ runner.os }}-${{matrix.cfg.opt}}-${{ env.cache-name }}-${{ hashFiles('**/*.cpp') }}
        restore-keys: |
          ${{ runner.os }}-${{matrix.cfg.opt}}-${{ env.cache-name }}-        
    - name: Cache libs
      id: cache-libs
      uses: actions/cache@v3
      env:
        cache-name: cache-install-libs
      with:
        path: |
          libs/boost/**
          libs/cairo/**
          libs/curl/**
          libs/fmod/**
          libs/FreeImage/**
          libs/freetype/**
          libs/glew/**
          libs/glfw/**
          libs/glm/**
          libs/json/**
          libs/pugixml/**
          libs/rtAudio/**
          libs/tess2/**
          libs/uriparser/**
          libs/utf8/**
          addons/ofxAssimpModelLoader/libs/**/
          addons/ofxKinect/libs/**/
          addons/ofxOpenCv/libs/**/
          addons/ofxSvg/libs/**/
          addons/ofxPoco/libs/**/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/apothecary/apothecary/formulas/**/*.sh') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-        
    - if: ${{ steps.cache-libs.outputs.cache-hit != 'true' }}
      # name: Download libs
      # continue-on-error: true
      run: ./scripts/$TARGET/download_libs.sh

    - name: rm-dev
      run: sudo rm -rf /Library/Developer
    - name: Build
      run: ./scripts/ci/osx/build.sh
      env:
        DEVELOPER_DIR: "/Applications/Xcode_13.4.1.app/Contents/Developer"
        SDKROOT: "/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
